### ISSUE TITLE
Error running COGEQC with the provided test dataset

### ISSUE THREAD

**Issue by mliannholland** [Arcadia-Science/noveltree#100]
### Description of the bug

I ran the test dataset command from the installation instructions and am running into an execution error at the COGEQC step of the pipeline. I am running all this in AWS EC2.

### Command used and terminal output

```console
ERROR ~ Error executing process > 'NOVELTREE:COGEQC (Orthogroup Summary)'

Caused by:
  Process `NOVELTREE:COGEQC (Orthogroup Summary)` terminated with an error exit status (1)


Command executed:

  # Assess orthogroups inferred using each inflation parameter, summarizing
  # how well they group proteins with the same domains together, as well as
  # other summary stats like number of ogs with >= the minimum # species,
  # per-species gene count per-og, etc.
  cogeqc_summarize_ogs.R Results_Inflation_5.25 4
  cat <<-END_VERSIONS > versions.yml
  "NOVELTREE:COGEQC":
      cogeqc: $( cat version.txt | head -n1 | sed "s/\[1] ‘//g" | sed "s/’//g" )
  END_VERSIONS




Command exit status:
  1

Command output:
  (empty)

Command error:
  System has not been booted with systemd as init system (PID 1). Can't operate.
  Failed to create bus connection: Host is down
```

**Comment by austinhpatton** [comment]
Hi @mliannholland - thanks for alerting us to this! I've implemented what I believe should be a fix to this issue (relates to broken/depracated UniProt return fields in the annotation module) in this PR (#101). We should hopefully be landing this very soon, and would love to know if it resolves the issue for you!

Thanks again,
Austin

**Comment by austinhpatton** [comment]
Hi again, @mliannholland - we've just landed the PR implementing this fix and have included it in a minor release (https://github.com/Arcadia-Science/noveltree/releases/tag/v1.0.2)! If you use this version to run NovelTree you should no longer have this issue! I'm going to close this for now, but please let me know if you continue to have issues or any new issues pop up!

Cheers,
Austin
