### ISSUE TITLE
singularity implementation

### ISSUE THREAD

**Issue by giacomomutti** [Arcadia-Science/noveltree#97]
### Description of feature

Dear devs, 

Are you planning to make Noveltree work with Singularity? Or anything else other than Docker?
If so, when more or less can we expect to have it?

Thank you and congrats for the awesome tool!

**Comment by austinhpatton** [comment]
Hi Giacomo, thanks for your interest in NovelTree, and my apologies for not getting back to you sooner! 

We don't currently have a plan to make NovelTree work with anything other than Docker, as our main focus at the moment is improving stability and efficiency, but perhaps after our next release we can be sure to make this happen!

**Comment by austinhpatton** [comment]
Hi Giacomo, thanks for your interest in NovelTree, and my apologies for not getting back to you sooner!

We don't currently have a plan to make NovelTree work with anything other than Docker, as our main focus at the moment is improving stability and efficiency, but perhaps after our next release we can be sure to make this happen!
